name: 🧑‍🏭📦🌍 Build / Publish

on:
  push:
    tags:
      - "build-workflow*"
      - "v[0-9]+.[0-9]+.[0-9]+*"
  pull_request:
    branches:
      - master
      - devel
  workflow_dispatch:

jobs:
  build:
    name: 🏗️👷 Build AutoTx
    runs-on: windows-2022

    env:
      NUGET_PACKAGES: ${{ github.workspace }}\.nuget\packages

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          lfs: "true"

      - name: 👷 Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: 🥇 Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v4.0

      - name: 🐛 Debug NuGet packages path
        run: |
          echo "NuGet packages path: $NUGET_PACKAGES"
        shell: pwsh

      # Cache NuGet packages to speed up build. Hash is based on project files,
      # which define the dependencies.
      - name: 💾 Cache 🥇 NuGet packages
        uses: actions/cache@v6
        id: nuget-packages
        env:
          cache-name: nuget-package-cache
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}

      - name: 🐛 Debug cached 💾 NuGet packages
        if: ${{ steps.nuget-packages.outputs.cache-hit == 'true' }}
        continue-on-error: true
        run: |
          echo "Using cached NuGet packages in directory: $NUGET_PACKAGES"
          ls $NUGET_PACKAGES

      - name: 💬 Using non-cached ❌💾 NuGet packages?
        if: ${{ steps.nuget-packages.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: echo "Not using cached NuGet packages."

      - name: 🧬 Restore NuGet packages from solution file
        run: nuget restore AutoTx.sln

      - name: 🏗️👷 Build solution
        run: .\Scripts\msbuild\build\release.cmd

      - name: 🏭📦🔨 Assemble package
        run: |
          $packageZipPath = .\Scripts\Make-Package.ps1
          echo "PACKAGE_ZIP_PATH=$packageZipPath" >> $env:GITHUB_ENV
        shell: pwsh

      - name: 🔍 Get filename from Zip file path
        run: |
          $packageZipName = [System.IO.Path]::GetFileName($env:PACKAGE_ZIP_PATH)
          echo "PACKAGE_ZIP_NAME=$packageZipName" >> $env:GITHUB_ENV
        shell: pwsh

      - name: 📝🔍 Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v3.1.0
        with:
          prerelease: true
          release_notes_file: RELEASE-NOTES.md

      - name: 🐛 Debug workspace
        run: |
          ls ${{ github.workspace }}

      - name: 🚀 Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: AutoTx-${{ github.ref_name }}
          generate_release_notes: false
          body_path: ${{ github.workspace }}/RELEASE-NOTES.md
          draft: false
          prerelease: true
          files: |
            ${{ env.PACKAGE_ZIP_PATH }}
